### ISSUE TITLE
AttributeError: 'DecisionTreeClassifier' object has no attribute 'partial_fit'

### ISSUE THREAD

**Issue by andrewcheng2016** [neurodata/SDTF#54]
When I call partial_fit(), the error below shows. 
AttributeError: 'DecisionTreeClassifier' object has no attribute 'partial_fit' 

It seems there is an error in the following code:
tree.partial_fit(X[indices, :], y[indices], classes=classes)

The tree should be the DecisionTreeClassifier from sklearn.tree, and it should not have a function called partial_fit

**Comment by PSSF23** [comment]
Follow the complete installation guide.
